services:
  portainer_agent:
    image: portainer/agent:2.21.0
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - 9001:9001
    restart: always
