services:
  agent:
    image: portainer/agent:2.21.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always

  portainer:
    image: portainer/portainer-ce:2.21.0
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
    restart: always
    depends_on:
      - agent

volumes:
  portainer_data:
